[package]
name = "dota2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
axum = "0.7.9"
backon = "1.2.0"
clap = { version = "4.5.20", features = ["derive"] }
clickhouse = "0.13.1"
env_logger = "0.11.5"
log = "0.4.22"
primitive-types = "0.13.1"
reqwest = { version = "0.12.8", features = ["socks"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["net", "rt-multi-thread", "io-std", "io-util", "macros", "fs"] }
